# -*- coding: utf-8 -*-
"""Motor semantico deterministico — FACHADA.

O motor vive em motor/engine/, um arquivo por responsabilidade (ver o __init__ de la).
Este modulo reexporta todo nome de topo — inclusive os privados que a suite exercita —
para que `from mcp_tiago_dados_abertos.motor import semantics_engine as se` continue
sendo a porta unica do motor.
"""
from __future__ import annotations

from .engine.ambiguidade import (
    _GRANULARITY_TERMS,
    _MODE_CLARIFY_HINTS,
    _MODE_LABELS,
    _assumption_note,
    _default_assumption_for_mode,
    _explicit_mode,
    _is_granularity_clarify,
    _is_mode_clarify,
    _question_has_granularity,
    _resolved_mode_clarify,
    check_ambiguity,
)
from .engine.contagem import (
    _AGGREGATE_PATTERNS,
    _COUNT_HARD_NEGATIVE,
    _COUNT_NEGATIVE,
    _COUNT_POSITIVE,
    _build_count_sql,
    _count_exclusion_filter,
    _detect_count_intent,
    _resolve_count_entity,
)
from .engine.fallback import (
    _BREAKDOWN_TERMS,
    _filter_fixes_spatial_single,
    _question_asks_breakdown,
    build_from_metrics,
    build_sin_rollup,
)
from .engine.metricas import _pattern_too_broad, _select_metric
from .engine.normalizacao import _norm, _phrase_match, _stem
from .engine.parametros import (
    _MESES,
    _MODE_TRIGGERS,
    _NON_TEXTUAL_TYPES,
    _PT_STOPWORDS,
    _SEMANTIC_AGG,
    _alias_usable,
    _build_col_index,
    _canonical_predicate,
    _escape_sql_value,
    _is_scalar_literal,
    _is_textual_column,
    _parse_filter,
    _resolve_dimension_filters,
    _unit_of,
    detect_mode,
    extract_params,
)
from .engine.patterns import (
    _MAX_ARQUIVOS_MES,
    _MONTH_PLACEHOLDERS,
    _RECENCIA_TERMS,
    _TEMPORAL_KEY_NAME_RE,
    _TEMPORAL_PARAM_KEYS,
    _TEMPORAL_PLACEHOLDERS,
    _YEAR_PLACEHOLDERS,
    FONTE_POR_DIA,
    FONTE_POR_MES,
    _fill_params,
    _fonte_dos_meses,
    _pede_recencia,
    _predicado_de_placeholder,
    _resolve_placeholder_from_question,
    _score_pattern,
    _sem_filtro_de_dimensao,
    _template_has_temporal_placeholder,
    dia_unico_da_pergunta,
    meses_da_pergunta,
    resolver_fonte,
)
from .engine.planejador import plan
from .engine.plano import (
    _ENERGY_VOLUME_UNITS,
    CONTRADICTION_KINDS,
    FLOW_KINDS,
    HARD_NO_SUM_KINDS,
    POWER_KINDS,
    Plan,
    _compute_summable,
    _summable_core,
    metric_summable_for_sql,
)
from .engine.template import (
    _anchor_year_to_latest,
    _apply_dimension_filters_ast,
    _deve_ancorar_recencia,
    _extract_predicate_column,
    _extract_predicate_columns_from_where,
    _find_main_select,
    _get_main_table_alias,
    _inject_dimension_filters,
    _inject_dimension_filters_regex,
    _is_valid_sql_statement,
    _mask_string_literals,
    _prepare_template_for_validation,
    _qualify_predicate_column,
    _replace_predicates_in_where,
    _select_has_joins,
    _sql_has_column_predicate,
    _trim_where_dimension_eqs,
    render_sql_pattern,
)

__all__ = [
    "CONTRADICTION_KINDS",
    "FLOW_KINDS",
    "FONTE_POR_DIA",
    "FONTE_POR_MES",
    "HARD_NO_SUM_KINDS",
    "POWER_KINDS",
    "Plan",
    "_AGGREGATE_PATTERNS",
    "_BREAKDOWN_TERMS",
    "_COUNT_HARD_NEGATIVE",
    "_COUNT_NEGATIVE",
    "_COUNT_POSITIVE",
    "_ENERGY_VOLUME_UNITS",
    "_GRANULARITY_TERMS",
    "_MAX_ARQUIVOS_MES",
    "_MESES",
    "_MODE_CLARIFY_HINTS",
    "_MODE_LABELS",
    "_MODE_TRIGGERS",
    "_MONTH_PLACEHOLDERS",
    "_NON_TEXTUAL_TYPES",
    "_PT_STOPWORDS",
    "_RECENCIA_TERMS",
    "_SEMANTIC_AGG",
    "_TEMPORAL_KEY_NAME_RE",
    "_TEMPORAL_PARAM_KEYS",
    "_TEMPORAL_PLACEHOLDERS",
    "_YEAR_PLACEHOLDERS",
    "_alias_usable",
    "_anchor_year_to_latest",
    "_apply_dimension_filters_ast",
    "_assumption_note",
    "_build_col_index",
    "_build_count_sql",
    "_canonical_predicate",
    "_compute_summable",
    "_count_exclusion_filter",
    "_default_assumption_for_mode",
    "_detect_count_intent",
    "_deve_ancorar_recencia",
    "_escape_sql_value",
    "_explicit_mode",
    "_extract_predicate_column",
    "_extract_predicate_columns_from_where",
    "_fill_params",
    "_filter_fixes_spatial_single",
    "_find_main_select",
    "_fonte_dos_meses",
    "_get_main_table_alias",
    "_inject_dimension_filters",
    "_inject_dimension_filters_regex",
    "_is_granularity_clarify",
    "_is_mode_clarify",
    "_is_scalar_literal",
    "_is_textual_column",
    "_is_valid_sql_statement",
    "_mask_string_literals",
    "_norm",
    "_parse_filter",
    "_pattern_too_broad",
    "_pede_recencia",
    "_phrase_match",
    "_predicado_de_placeholder",
    "_prepare_template_for_validation",
    "_qualify_predicate_column",
    "_question_asks_breakdown",
    "_question_has_granularity",
    "_replace_predicates_in_where",
    "_resolve_count_entity",
    "_resolve_dimension_filters",
    "_resolve_placeholder_from_question",
    "_resolved_mode_clarify",
    "_score_pattern",
    "_select_has_joins",
    "_select_metric",
    "_sem_filtro_de_dimensao",
    "_sql_has_column_predicate",
    "_stem",
    "_summable_core",
    "_template_has_temporal_placeholder",
    "_trim_where_dimension_eqs",
    "_unit_of",
    "build_from_metrics",
    "build_sin_rollup",
    "check_ambiguity",
    "detect_mode",
    "dia_unico_da_pergunta",
    "extract_params",
    "meses_da_pergunta",
    "metric_summable_for_sql",
    "plan",
    "render_sql_pattern",
    "resolver_fonte",
]
